"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const user_route_1 = __importDefault(require("./user.route"));
const product_route_1 = __importDefault(require("./product.route"));
const catalog_route_1 = __importDefault(require("./catalog.route"));
const category_route_1 = __importDefault(require("./category.route"));
const upload_route_1 = __importDefault(require("./upload.route"));
const brand_route_1 = __importDefault(require("./brand.route"));
const cart_route_1 = __importDefault(require("./cart.route"));
const order_route_1 = __importDefault(require("./order.route"));
const review_route_1 = __importDefault(require("./review.route"));
const router = express_1.default.Router();
router.use("/api/v1", user_route_1.default);
router.use("/api/v1", product_route_1.default);
router.use("/api/v1", catalog_route_1.default);
router.use("/api/v1", category_route_1.default);
router.use("/api/v1", upload_route_1.default);
router.use("/api/v1", brand_route_1.default);
router.use("/api/v1", cart_route_1.default);
router.use("/api/v1", order_route_1.default);
router.use("/api/v1", review_route_1.default);
exports.default = router;
