import express from "express";
import user from "./user.route";
import product from "./product.route";
import catalog from "./catalog.route";
import category from "./category.route";
import upload from "./upload.route";
import brand from "./brand.route";
import cart from "./cart.route";
import order from "./order.route";
import review from "./review.route";
import conversation from "./conversation.route";
import message from "./message.route";
const router = express.Router();

router.use("/api/v1", user);
router.use("/api/v1", product);
router.use("/api/v1", catalog);
router.use("/api/v1", category);
router.use("/api/v1", upload);
router.use("/api/v1", brand);
router.use("/api/v1", cart);
router.use("/api/v1", order);
router.use("/api/v1", review);
router.use("/api/v1", conversation);
router.use("/api/v1", message);
export default router;
